networks:
  app-mabos:
    external: false

services:

  spa:
    image: mabru/mabos-spa:latest
    pull_policy: always
    restart: always
    #ports:
    #  - 4200:80
    networks:
      - app-mabos

  backent:
    image: mabru/mabos-backent:latest
    pull_policy: always
    restart: always
    depends_on:
      - postgres
      - keycloak
    #ports:
    #  - 8080:8080
    environment:
      CORS_ALLOWED_ORIGIN: https://abos.mab.rocks
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK-SET-URI: "http://keycloak:8080/realms/mabos-realm/protocol/openid-connect/certs"
    networks:
      - app-mabos

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
    #ports:
    #  - 5432:5432
    volumes:
      # init db
      - ./deployment/db:/docker-entrypoint-initdb.d/
    networks:
      - app-mabos

  keycloak:
    image: quay.io/keycloak/keycloak:23.0.0
    depends_on:
      - postgres
    command: ['start-dev', '--import-realm']
    #command: ['start-dev']
    #ports:
    #  - 8180:8080
    environment:
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
      KC_DB: postgres
      KC_DB_URL: ${KC_DB_URL}
      KC_DB_PASSWORD: ${KC_DB_PASSWORD}
      KC_DB_USERNAME: ${KC_DB_USERNAME}
      KC_HOSTNAME: iam.mab.rocks
      KC_PROXY: edge
      TZ: Europe/Zurich
    volumes:
      - ./deployment/mabos-realm.json:/opt/keycloak/data/import/mabos-realm.json
    networks:
      - app-mabos
