services:

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: mabos-db
      POSTGRES_PASSWORD: mypw
      POSTGRES_USER: mabos-db-admin
    ports:
      - 5432:5432
    volumes:
      # init db
      - ./deployment/db:/docker-entrypoint-initdb.d/

  keycloak:
    # testuser: ?
    # Export keycloak realm - one command
    # docker exec -i mabos-keycloak-1 /bin/sh -c '/opt/keycloak/bin/kc.sh export --realm mabos-realm --file /tmp/realm.json --users realm_file' && \
    # docker cp mabos-keycloak-1:/tmp/realm.json ./deployment/realm.json

    image: quay.io/keycloak/keycloak:23.0.0
    depends_on:
      - postgres
    command: ['start-dev', '--import-realm']
    #command: ['start-dev']
    ports:
      - 8180:8080
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres:5432/mabos-db?currentSchema=keycloak
      KC_DB_PASSWORD: mypw
      KC_DB_USERNAME: mabos-db-admin
      TZ: Europe/Zurich
    volumes:
      - ./deployment/realm-mabos-local.json:/opt/keycloak/data/import/realm-mabos-local.json

